package com.metalsa.core.utils;

/**
 *
 * @author APOMR10051
 */
public enum Estatus {
    POR_COTIZAR("POR COTIZAR"),
    SEL_COTIZACION("SEL COTIZACION"),
    SELECCIONADA("SELECCIONADA"),
    SELECCIONADO("SELECCIONADO"),
    SOL_INFO_REQUISITOR_COMPRADOR("SOL INFO REQ-COM"),
    REGRESADA_A_COMPRADOR("REGRESADA A COMPRADOR"),
    SOL_INFO_COMPRADOR_REQUISITOR("SOL INFO COM-REQ"),
    DECLINADA("DECLINADA"),
    ACTIVA("ACTIVA"),
    INACTIVA("INACTIVA"),
    SIN_SELECCIONAR("SIN SELECCIONAR"),
    EN_PROCESO("EN PROCESO"),
    PENDIENTE("PENDIENTE"),
    COTIZADA("COTIZADA"),
    CANCELADA("CANCELADA"),
    POR_APROBAR("POR APROBAR"),
    APROBACION_PROYECTO("APROBACION PROYECTO"),
    SOL_INFO_COMPRADOR_PROVEEDOR("SOL INFO COMPRADOR-PROVEEDOR"),
    SOL_INFO_PROVEEDOR_COMPRADOR("SOL INFO PROVEEDOR-COMPRADOR"),
    NO_SELECCIONADA("NO SELECCIONADA"),
    APROBADA("APROBADA"),
    REGRESADA_POR_COMPRADOR("REGRESADA60"),
    REGRESADA_POR_COMPRADOR_RFQ("REGRESADA61"),
    CANTIDAD_MODIFICADA("CANTIDAD MODIFICADA"),
    CANTIDAD_MODIFICADA_ENG("QUANTITY ALTERED"),
    COTIZADA_POR_PROVEEDOR("COTIZADA POR PROVEEDOR"),
    PUBLICADO("PUBLICADO"),
    NO_PUBLICADO("NO PUBLICADO"),
    EN_EDICION("EN EDICION"),
    REGRESADA("REGRESADA"),
    CERRADA("CERRADA");
    
    private final String desc;

    private Estatus(String desc) {
        this.desc = desc;
    }

    public String getDesc() {
        return desc;
    }
    
    public boolean equals(String desc) {
        return this.desc != null && desc != null && this.desc.equals(desc);
    }
}
